spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: alexepure70@gmail.com
    password: erbqvuiaixwpvfqz
    port: '587'
server:
  port: 8080
api:
  base:
    path: http://localhost:8080/login
